---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://openedx.atlassian.net/wiki/display/OpenOPS
# code style: https://openedx.atlassian.net/wiki/display/OpenOPS/Ansible+Code+Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
##
# Defaults for role hermes
# 

#
# vars are namespaced with the module name.
#

hermes_user: hermes
hermes_role_name: hermes
hermes_service_name: hermes
hermes_source_repo: https://github.com/edx/hermes.git
hermes_version: master
hermes_app_dir: "{{ COMMON_APP_DIR }}/{{ hermes_service_name }}"
hermes_code_dir: "{{ hermes_app_dir }}/{{hermes_service_name}}"
hermes_venv_dir: "{{ hermes_app_dir }}/venvs/{{ hermes_service_name }}"
hermes_venv_bin: "{{ hermes_venv_dir }}/bin"
HERMES_SERVICE_CONFIG: []
HERMES_NEWRELIC_APPNAME: "{{ COMMON_ENVIRONMENT }}-{{ COMMON_DEPLOYMENT }}-{{hermes_service_name}}"
hermes_environment:
  PATH: "{{ hermes_venv_dir }}/bin:{{ ansible_env.PATH }}"
#
# OS packages
#

hermes_debian_pkgs: []

hermes_redhat_pkgs: []
