---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://openedx.atlassian.net/wiki/display/OpenOPS
# code style: https://openedx.atlassian.net/wiki/display/OpenOPS/Ansible+Code+Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
##
# Defaults for role hermes
# 

#
# vars are namespaced with the module name.
#
hermes_role_name: hermes

#
# OS packages
#

hermes_debian_pkgs: []

hermes_redhat_pkgs: []
